import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { dark } from "@clerk/themes";

import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton,
} from "@clerk/nextjs";
import { Button } from "~/components/ui/button";

import Link from "next/link";
import ScrabbleTile from "~/components/ui/scrabble-tile";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
  return (
    <header className="sticky top-0 flex h-16 items-center gap-4 border-b bg-background px-4 md:px-6">
      <nav className="full container flex flex-row items-center justify-between gap-6 text-lg font-medium">
        <Link
          href="/"
          className="flex items-center gap-0 text-lg font-semibold md:text-base"
        >
          <div className="flex gap-1">
            {"SCRABBLE".split("").map((letter, index) => (
              <ScrabbleTile
                key={index}
                letter={letter}
                size={2}
                theme="gruvbox"
              />
            ))}
          </div>
        </Link>

        <SignedOut>
          <SignInButton>
            <Button size={"lg"}>Sign In</Button>
          </SignInButton>
        </SignedOut>
        <SignedIn>
          <UserButton />
        </SignedIn>
      </nav>
    </header>
  );
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className="dark">
          <TopNav />

          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
